version: '3.8'

services:
  films-app:
    build: ./
    command: ./app
    ports:
    - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5