basePath: /
definitions:
  handler.signInInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  handler.signUpInput:
    properties:
      email:
        type: string
      gender:
        type: string
      password:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - email
    - gender
    - password
    - role
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: WEB API
  title: Film API
  version: "1.0"
paths:
  /api/account/sign_in:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses: {}
      summary: SignIn
      tags:
      - Account
  /api/account/sign_up:
    post:
      consumes:
      - application/json
      description: sign up the user
      parameters:
      - description: credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signUpInput'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Information
      tags:
      - Account
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
